// Package booking defines the core domain entities for the native booking engine.
package booking

import "time"

// BookingStatus represents the current state of a booking lifecycle.
type BookingStatus string

const (
	StatusPending   BookingStatus = "PENDING"
	StatusConfirmed BookingStatus = "CONFIRMED"
	StatusCancelled BookingStatus = "CANCELLED"
)

// AppointmentMode captures whether a booking is in person or remote.
type AppointmentMode string

const (
	AppointmentModeInPerson AppointmentMode = "IN_PERSON"
	AppointmentModeRemote   AppointmentMode = "REMOTE"
)

// GoogleSyncStatus tracks lifecycle of async Google synchronization.
type GoogleSyncStatus string

const (
	GoogleSyncNotSynced    GoogleSyncStatus = "NOT_SYNCED"
	GoogleSyncPending      GoogleSyncStatus = "PENDING"
	GoogleSyncSynced       GoogleSyncStatus = "SYNCED"
	GoogleSyncDeletePend   GoogleSyncStatus = "DELETE_PENDING"
	GoogleSyncDeleteSynced GoogleSyncStatus = "DELETE_SYNCED"
	GoogleSyncFailed       GoogleSyncStatus = "FAILED"
)

// Booking represents a scheduled time slot for a resource, mapping frontend trace IDs to Shopify transactions.
type Booking struct {
	ID                    string           `json:"id"`          // Generated by frontend (traceId)
	ResourceIDs           []string         `json:"resourceIds"` // The services or items being booked
	LeadID                string           `json:"leadId"`      // The mandatory identity anchor
	LeadEmail             string           `json:"leadEmail,omitempty"`
	LeadName              string           `json:"leadName,omitempty"`
	StartTime             time.Time        `json:"startTime"`                // Enforced UTC
	EndTime               time.Time        `json:"endTime"`                  // Enforced UTC
	Status                BookingStatus    `json:"status"`                   // PENDING, CONFIRMED, or CANCELLED
	ShopifyOrderID        *string          `json:"shopifyOrderId,omitempty"` // Optional: Populated upon successful checkout webhook
	AppointmentMode       AppointmentMode  `json:"appointmentMode"`
	GoogleEventID         *string          `json:"googleEventId,omitempty"`
	GoogleMeetURL         *string          `json:"googleMeetURL,omitempty"`
	GoogleSyncStatus      GoogleSyncStatus `json:"googleSyncStatus"`
	GoogleLastError       *string          `json:"googleLastError,omitempty"`
	ConfirmationEmailSent bool             `json:"confirmationEmailSent"`
	LinkAddedEmailSent    bool             `json:"linkAddedEmailSent"`
	CreatedAt             time.Time        `json:"createdAt"`
}

// BookingMetrics contains aggregated statistics for booking volume and conversion.
type BookingMetrics struct {
	TotalMonthlyConfirmed int `json:"totalMonthlyConfirmed"`
	TotalAnnualConfirmed  int `json:"totalAnnualConfirmed"`
	TotalWeeklyConfirmed  int `json:"totalWeeklyConfirmed"`
	LeadConversionAnchor  int `json:"leadConversionAnchor"`
	PendingLast24h        int `json:"pendingLast24h"`
	ConfirmedLast24h      int `json:"confirmedLast24h"`
}
