// Package booking defines the core domain entities for the native booking engine.
package booking

import "time"

// BookingStatus represents the current state of a booking lifecycle.
type BookingStatus string

const (
	StatusPending   BookingStatus = "PENDING"
	StatusConfirmed BookingStatus = "CONFIRMED"
	StatusCancelled BookingStatus = "CANCELLED"
)

// Booking represents a scheduled time slot for a resource, mapping frontend trace IDs to Shopify transactions.
type Booking struct {
	ID             string        `json:"id"`                       // Generated by frontend (traceId)
	ResourceIDs    []string      `json:"resourceIds"`              // The services or items being booked
	LeadID         string        `json:"leadId"`                   // The mandatory identity anchor
	StartTime      time.Time     `json:"startTime"`                // Enforced UTC
	EndTime        time.Time     `json:"endTime"`                  // Enforced UTC
	Status         BookingStatus `json:"status"`                   // PENDING, CONFIRMED, or CANCELLED
	ShopifyOrderID *string       `json:"shopifyOrderId,omitempty"` // Optional: Populated upon successful checkout webhook
	CreatedAt      time.Time     `json:"createdAt"`
}
